### ISSUE TITLE
Bern Conference TODO

### ISSUE THREAD

**Issue by astonedf** [usi-sweet-sure/EnsuredEnergy_GDScript#10]
- [x] Player can only implement one campaign/policy per turn - notification
- [x] Upgrade Post it need seasonality into calculations
- [ ] Show how much each type of plant produces on the graph / infobar(?)
- [ ] Better tutorial......
- [x] Add production costs to building cost in build menu
- [x] Add % to demand policy text
- [x] Graphs button on 2nd turn
- [ ] Do we want to decomission powerplants?
- [x] Negative co2 emissions in green
- [x] Set import to 0 at the start of each turn
- [x] Import slider max is max import amount
- [x] Block zoom during tutorial
- [x] Block all map movement during tutorial (mouse drag and arrows)
